name: cd

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 30
    
        steps:
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: "1.24.0"

            - name: Checkout code
              uses: actions/checkout@v1
            
            - name: Make build
              run: ./scripts/buildprod.sh