name: ci

on:
    pull_request:
            branches: [main]

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        
        steps:
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: "1.24.0"

            - name: Checkout code
              uses: actions/checkout@v1

            - name: Force Failure
              run: exit 1